### ISSUE TITLE
label_ranking_average_precision_score

### ISSUE THREAD

**Issue by shantanuo** [kavgan/nlp-in-practice#3]
mrr has been implemented as a class in sklearn called "label_ranking_average_precision_score".

https://scikit-learn.org/stable/modules/generated/sklearn.metrics.label_ranking_average_precision_score.html

The code in "Text Classification with Logistic Regression.ipynb" file will be much shorter if it is used.

**Comment by kavgan** [comment]
I did see that, but I remember not wanting to use it for some reason. 🤔 I'm trying to recall why.

**Comment by shantanuo** [comment]
Here is a simplified version:
https://gist.github.com/shantanuo/d2cbbe4f77e0eba880010ef9bbadf82f
